'use client';

import React, { useState } from 'react';
import { ArrowRight, Database, Terminal } from 'lucide-react';

export default function LoginPage() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setIsLoading(true);

    try {
      const res = await fetch('/api/auth/login', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email, password }),
      });

      const data = await res.json();

      if (!res.ok) {
        throw new Error(data.error || 'Failed to login');
      }

      // Force a full refresh to clear any cached states and hit the middleware
      window.location.href = '/';
    } catch (err: any) {
      setError(err.message);
      setIsLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex bg-[#000000] text-slate-100 font-sans selection:bg-cyan-500/30 selection:text-cyan-200">
      
      {/* Left side: Beautiful Hero Image */}
      <div className="hidden lg:flex w-1/2 relative bg-[#090d16] border-r border-[#222] overflow-hidden items-center justify-center">
        {/* We use an image generated by the AI for a premium 3D data center look */}
        <div 
          className="absolute inset-0 bg-cover bg-center opacity-80"
          style={{ backgroundImage: 'url(/login-hero.jpg)' }}
        />
        {/* Gradient overlay to smoothly blend into the dark theme */}
        <div className="absolute inset-0 bg-gradient-to-t from-black via-black/40 to-transparent" />
        <div className="absolute inset-0 bg-gradient-to-r from-black/60 to-transparent" />
        
        {/* Branding over the image */}
        <div className="relative z-10 w-full max-w-lg p-12 text-left mt-auto mb-12">
          <div className="inline-flex items-center justify-center p-3 bg-white/10 backdrop-blur-md rounded-2xl border border-white/20 mb-6">
            <Database className="w-8 h-8 text-white" />
          </div>
          <h1 className="text-5xl font-extrabold text-white tracking-tight leading-tight mb-4">
            SGE <br /> Data Hub
          </h1>
          <p className="text-lg text-neutral-300 font-medium">
            The central control plane for all infrastructure, databases, and microservices across Shree Ganesh Enterprises.
          </p>
        </div>
      </div>

      {/* Right side: Login Form */}
      <div className="w-full lg:w-1/2 flex items-center justify-center p-8 relative">
        <div className="w-full max-w-[420px] space-y-8 relative z-10">
          
          <div className="space-y-2">
            <h2 className="text-3xl font-bold text-white tracking-tight">Welcome back</h2>
            <p className="text-sm text-neutral-400">Sign in to your control plane to manage deployments and data.</p>
          </div>

          <form onSubmit={handleLogin} className="space-y-6" autoComplete="off">
            {error && (
              <div className="p-3 bg-rose-500/10 border border-rose-500/20 rounded-lg text-rose-400 text-sm font-medium">
                {error}
              </div>
            )}

            <div className="space-y-5">
              <div className="space-y-2">
                <label className="text-xs font-semibold text-neutral-400 uppercase tracking-wider">Email Address</label>
                <input
                  type="email"
                  required
                  autoComplete="off"
                  data-lpignore="true"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  className="w-full bg-[#0a0a0a] border border-[#333] rounded-xl px-4 py-3 text-white text-sm focus:outline-none focus:border-white transition-colors"
                  placeholder="amcmep247@gmail.com"
                />
              </div>

              <div className="space-y-2">
                <label className="text-xs font-semibold text-neutral-400 uppercase tracking-wider">Password</label>
                <input
                  type="password"
                  required
                  autoComplete="new-password"
                  data-lpignore="true"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  className="w-full bg-[#0a0a0a] border border-[#333] rounded-xl px-4 py-3 text-white text-sm focus:outline-none focus:border-white transition-colors"
                  placeholder="Enter your password"
                />
              </div>
            </div>

            <button
              type="submit"
              disabled={isLoading}
              className="w-full bg-white hover:bg-neutral-200 text-black font-semibold rounded-xl px-4 py-3 text-sm transition-colors flex items-center justify-center gap-2 disabled:opacity-50"
            >
              {isLoading ? (
                <span className="w-4 h-4 border-2 border-black/20 border-t-black rounded-full animate-spin" />
              ) : (
                <>
                  Continue <ArrowRight className="w-4 h-4" />
                </>
              )}
            </button>
          </form>

          <div className="pt-8 text-center text-xs text-neutral-600 font-mono">
            <Terminal className="w-3 h-3 inline-block mr-1 align-text-bottom" />
            SGE Data Hub Secure Portal
          </div>
        </div>
      </div>
    </div>
  );
}
